SET (ACE_INCLUDE_DIRS $ENV{ACE_ROOT})
SET (ACE_LIBRARY_DIRS $ENV{ACE_ROOT}/lib)

IF (UNIX)
	SET (ACE_LIBRARIES ACE)

	SET (ACE_DEFINITIONS ${ACE_DEFINITIONS} -D_GNU_SOURCE)
ELSEIF (WIN32)
	SET (ACE_LIBRARIES debug ACEd optimized ACE)
	SET (ACE_DEFINITIONS ${ACE_DEFINITIONS} -D_CRT_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE )

	IF (MSVC)
		# Disable warning C4706:
		#   assignment within conditional expression
		SET (ACE_DEFINITIONS ${ACE_DEFINITIONS} /wd4706)
	ENDIF (MSVC)
ENDIF (UNIX)
